In [5]:
import math
def recCurve(a, b, x):
    return a * math.log(x+1, 10)**(b * math.log(x+12, 10)) + 500

In [6]:
a = 1.4
b = 1.682

In [8]:
round(recCurve(a,b, 2500))

2028

In [4]:
!pip install pm4py

Collecting pm4py
  Downloading pm4py-2.2.25-py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 4.9 MB/s eta 0:00:01
Collecting deprecation
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: lxml in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (4.6.3)
Collecting cvxopt
  Downloading cvxopt-1.3.0-cp39-cp39-macosx_10_9_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 13.4 MB/s eta 0:00:01
Requirement already satisfied: pytz in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (2021.3)
Requirement already satisfied: numpy>=1.19.5 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (1.20.3)
Requirement already satisfied: networkx in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (2.6.3)
Requirement already satisfied: tqdm in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (4.62.3)
Collecting pyvis
  Using cached pyvis-0.2.1.tar.gz (21 kB)
Requirement already satisfied: sympy in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (1.9)
Collecting stringdist
  Using cached StringDist-1.0.9.tar.gz (7.4 kB)
Requirement already satisfied: scipy in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (1.7.1)
Requirement already satisfied: pandas>=1.1.5 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (1.3.4)
Requirement already satisfied: matplotlib in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (3.4.3)
Collecting graphviz
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 2.9 MB/s eta 0:00:01
Requirement already satisfied: intervaltree in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pm4py) (3.1.0)
Collecting jsonpickle
  Using cached jsonpickle-2.2.0-py2.py3-none-any.whl (39 kB)
Collecting pydotplus
  Using cached pydotplus-2.0.2.tar.gz (278 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.1.5->pm4py) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.5->pm4py) (1.16.0)
Requirement already satisfied: packaging in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from deprecation->pm4py) (21.0)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from intervaltree->pm4py) (2.4.0)
Requirement already satisfied: cycler>=0.10 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->pm4py) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->pm4py) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->pm4py) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->pm4py) (8.4.0)
Requirement already satisfied: jinja2>=2.9.6 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pyvis->pm4py) (2.11.3)
Requirement already satisfied: ipython>=5.3.0 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pyvis->pm4py) (7.29.0)
Requirement already satisfied: setuptools>=18.5 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (58.0.4)
Requirement already satisfied: appnope in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.1.2)
Requirement already satisfied: matplotlib-inline in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.1.2)
Requirement already satisfied: pexpect>4.3 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (4.8.0)
Requirement already satisfied: pygments in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (2.10.0)
Requirement already satisfied: pickleshare in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.7.5)
Requirement already satisfied: decorator in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (5.1.0)
Requirement already satisfied: backcall in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (3.0.20)
Requirement already satisfied: traitlets>=4.2 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (5.1.0)
Requirement already satisfied: jedi>=0.16 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.3.0->pyvis->pm4py) (0.8.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from jinja2>=2.9.6->pyvis->pm4py) (1.1.1)
Requirement already satisfied: ptyprocess>=0.5 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.3.0->pyvis->pm4py) (0.7.0)
Requirement already satisfied: wcwidth in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->pyvis->pm4py) (0.2.5)
Requirement already satisfied: mpmath>=0.19 in /Users/teddy/opt/anaconda3/lib/python3.9/site-packages (from sympy->pm4py) (1.2.1)
Building wheels for collected packages: pydotplus, pyvis, stringdist
  Building wheel for pydotplus (setup.py) ... done
  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24575 sha256=5ed514a083bcc107428a630589764fc733767d98ff6331753c4e62f85382e159
  Stored in directory: /Users/teddy/Library/Caches/pip/wheels/89/e5/de/6966007cf223872eedfbebbe0e074534e72e9128c8fd4b55eb
  Building wheel for pyvis (setup.py) ... done
  Created wheel for pyvis: filename=pyvis-0.2.1-py3-none-any.whl size=23688 sha256=39cd48fece509db538151d80c61d19e107139cdd43c3e4dc4cbb7ae50f72da99
  Stored in directory: /Users/teddy/Library/Caches/pip/wheels/05/fb/37/c8dfe38ad21c8cc91f40a0f9e0196cfdd4534e817d0416a0ae
  Building wheel for stringdist (setup.py) ... done
  Created wheel for stringdist: filename=StringDist-1.0.9-cp39-cp39-macosx_10_9_x86_64.whl size=7849 sha256=de482adcc6a67bc7c62f33ba83a5e30f8f9d520a0b352e296b7085e9defc5e90
  Stored in directory: /Users/teddy/Library/Caches/pip/wheels/77/24/44/b12b9612fd07e141e6b4f1bb2001c621515bd0cac1014a783a
Successfully built pydotplus pyvis stringdist
Installing collected packages: jsonpickle, stringdist, pyvis, pydotplus, graphviz, deprecation, cvxopt, pm4py
Successfully installed cvxopt-1.3.0 deprecation-2.1.0 graphviz-0.20.1 jsonpickle-2.2.0 pm4py-2.2.25 pydotplus-2.0.2 pyvis-0.2.1 stringdist-1.0.9

In [58]:

from pm4py.objects.conversion.log import converter as xes_converter
from pm4py.objects.log.importer.xes import importer as xes_importer

log = xes_importer.apply('/Users/teddy/Documents/TU_e/ThirdYear/Quartile_4/BEP/edbn_BEP/input_files/BPIC2015FULL.xes')
loadedf = xes_converter.apply(log, variant=xes_converter.Variants.TO_DATA_FRAME)

parsing log, completed traces ::   0%|          | 0/5649 [00:00<?, ?it/s]

In [65]:
max(pd.iloc[0:52216,0])

'2015-03-03 00:00:00'

In [28]:
pd.columns

Index(['dateFinished', 'org:resource', 'activityNameEN',
       'lifecycle:transition', 'time:timestamp', 'action_code', 'question',
       'activityNameNL', 'concept:name', 'dueDate', 'planned',
       'monitoringResource', 'case:termName', 'case:startDate',
       'case:Responsible_actor', 'case:caseStatus', 'case:endDatePlanned',
       'case:endDate', 'case:parts', 'case:requestComplete',
       'case:concept:name', 'case:last_phase', 'case:SUMleges',
       'case:case_type', 'case:IDofConceptCase', 'case:landRegisterID',
       'case:caseProcedure', 'case:Includes_subCases', 'dateStop',
       'prevdateFinished'],
      dtype='object')

In [48]:
#pd.iloc[:52217,:]['dateFinished']
#pd['prevdateFinished'] = pd['dateFinished'].shift(-1)
#print(pd['dateFinished'][len(pd['dateFinished']) -1] - pd['dateFinished'][0])
from datetime import datetime
d1 = datetime.strptime(pd['completeTime'][52217 + 44354 + 59681], "%Y-%m-%d %H:%M:%S")
d2 = datetime.strptime(pd['completeTime'][52216 + 44354 + 59681 + 47293 ], "%Y-%m-%d %H:%M:%S")
#1: 88, 2:94, 3: 876, 4:35, 5:61
time = d1 - d2

In [49]:
d2 - d1

datetime.timedelta(days=35)

In [ ]:
pd.to_csv(path_or_buf = '/Users/teddy/Documents/TU_e/ThirdYear/Quartile_4/BEP/edbn_BEP/Data/BPIC15_FULL.csv', index = False)

In [13]:
pd.rename(columns = {'org:resource':'role', 'activityNameEN':'event', 'time:timestamp':'completeTime', 'case:concept:name':'case'}, inplace = True)

In [14]:
pd['new_event'] = pd['concept:name'] + pd['lifecycle:transition']

In [29]:
pd.rename(columns = {'org:resource':'role', 'activityNameEN':'event', 'dateFinished':'completeTime', 'case:concept:name':'case'}, inplace = True)

In [18]:
pd = pd.iloc[:200000, :]

In [20]:
pd.shape

(200000, 19)

In [9]:
pd['Action'].unique()

array(['Created', 'statechange', 'Deleted', 'Obtained', 'Released'],
      dtype=object)

In [29]:
pd['new_event'].unique()

array(['CreatedA_Create Application', 'statechangeA_Submitted',
       'CreatedW_Handle leads', 'DeletedW_Handle leads',
       'CreatedW_Complete application', 'statechangeA_Concept',
       'ObtainedW_Complete application', 'ReleasedW_Complete application',
       'statechangeA_Accepted', 'CreatedO_Create Offer',
       'statechangeO_Created', 'statechangeO_Sent (mail and online)',
       'DeletedW_Complete application', 'CreatedW_Call after offers',
       'ObtainedW_Call after offers', 'statechangeA_Complete',
       'ReleasedW_Call after offers', 'DeletedW_Call after offers',
       'CreatedW_Validate application', 'ObtainedW_Validate application',
       'statechangeA_Validating', 'statechangeO_Returned',
       'ReleasedW_Validate application', 'DeletedW_Validate application',
       'CreatedW_Call incomplete files',
       'ObtainedW_Call incomplete files', 'statechangeA_Incomplete',
       'ReleasedW_Call incomplete files',
       'DeletedW_Call incomplete files', 'statechangeO_Accepted',
       'statechangeA_Pending', 'statechangeA_Denied',
       'statechangeO_Refused', 'statechangeO_Cancelled',
       'ObtainedW_Handle leads', 'statechangeA_Cancelled',
       'statechangeO_Sent (online only)', 'ReleasedW_Handle leads',
       'CreatedW_Assess potential fraud',
       'ObtainedW_Assess potential fraud',
       'ReleasedW_Assess potential fraud',
       'DeletedW_Assess potential fraud',
       'CreatedW_Personal Loan collection',
       'ObtainedW_Personal Loan collection',
       'ReleasedW_Personal Loan collection'], dtype=object)

In [15]:
pd.rename(columns = {'event':'eventID', 'new_event':'event'}, inplace = True)

In [26]:
pd['completeTime'].sort_values().tolist()[-1]

Timestamp('2017-02-01 14:11:03.499000+0000', tz='UTC')

In [165]:
b1

,completeTime,role,event,lifecycle:transition,time:timestamp,action_code,question,activityNameNL,concept:name,dueDate,...,case,case:last_phase,case:SUMleges,case:case_type,case:IDofConceptCase,case:landRegisterID,case:caseProcedure,case:Includes_subCases,dateStop,prevdateFinished
8114,2010-10-07 14:57:22,560872,register submission date request,complete,2009-11-18 00:00:00+01:00,01_HOOFD_010,5-10-2010 0:00:00,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-10 14:43:08+02:00,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-10-07 14:57:22
8115,2010-10-07 14:57:22,560872,phase application received,complete,2009-11-20 14:57:14+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-11-30 16:22:53
8170,2010-10-12 10:05:12,560925,phase application received,complete,2009-11-25 09:54:56+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
8169,2010-10-12 10:05:12,560925,register submission date request,complete,2009-11-19 00:00:00+01:00,01_HOOFD_010,EMPTY,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-14 10:51:19+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
8172,2010-10-12 10:05:12,560925,forward to the competent authority,complete,2009-11-25 09:56:15+01:00,01_HOOFD_040,False,doorsturen aan bevoegd gezag,01_HOOFD_040,2010-10-17 09:56:10+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7369,2015-03-03 00:00:00,560912,record date of decision environmental permit,complete,2014-04-18 02:00:00+02:00,01_HOOFD_490_5,EMPTY,registreren datum besluit omgevingsvergunning2,01_HOOFD_490_5,NaN,...,case_id_163,Beschikking verzonden,5019.30600,557669,12663987.0,12663844.0,NaN,NaN,NaN,2015-01-08 00:00:00
7368,2015-03-03 00:00:00,560912,set decision phase decision permitting decided,complete,2014-04-18 02:00:00+02:00,01_HOOFD_490_5a,EMPTY,instellen besluitfase:besluit vergunnen besloten,01_HOOFD_490_5a,NaN,...,case_id_163,Beschikking verzonden,5019.30600,557669,12663987.0,12663844.0,NaN,NaN,NaN,2015-03-03 00:00:00
7367,2015-03-03 00:00:00,560912,start decision phase decision permitting sent,complete,2014-04-18 02:00:00+02:00,01_HOOFD_510_2a,EMPTY,instellen besluitfase:besluit vergunnen verzonden,01_HOOFD_510_2a,NaN,...,case_id_163,Beschikking verzonden,5019.30600,557669,12663987.0,12663844.0,NaN,NaN,NaN,2015-03-03 00:00:00
7365,2015-03-03 00:00:00,560912,enter senddate decision environmental permit,complete,2014-04-16 02:00:00+02:00,01_HOOFD_510_3,EMPTY,invoeren verzenddatum beschikking omgevingsver...,01_HOOFD_510_3,NaN,...,case_id_163,Beschikking verzonden,5019.30600,557669,12663987.0,12663844.0,NaN,NaN,NaN,2015-03-03 00:00:00
7687,2015-03-03 00:00:00,560912,enter senddate decision,complete,2014-04-16 02:00:00+02:00,01_HOOFD_510_4,EMPTY,invoeren verzenddatum beschikking,01_HOOFD_510_4,NaN,...,case_id_171,Beschikking verzonden,1277.48220,557669,12785089.0,12784486.0,NaN,NaN,NaN,2015-03-03 00:00:00

#

In [23]:
#30057

In [31]:
len(pd['event'][30057:].tolist())

1172210

In [96]:
import pandas as pd
tab = pd.read_csv('/Users/teddy/Documents/TU_e/ThirdYear/Quartile_4/BEP/edbn_BEP/Data/BPIC15_FULL.csv')

/Users/teddy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (16,26,27,28) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [97]:
tab['completeTime']

0         2014-04-14 00:00:00
1         2014-04-14 00:00:00
2         2014-04-14 00:00:00
3         2014-04-14 00:00:00
4         2014-04-14 00:00:00
                 ...
262623    2014-03-12 00:00:00
262624    2014-03-12 00:00:00
262625    2014-03-12 00:00:00
262626    2014-03-12 00:00:00
262627    2014-03-12 00:00:00
Name: completeTime, Length: 262628, dtype: object

In [98]:
b1 = tab.iloc[0:52217, :].sort_values(by = 'completeTime')
b2 = tab.iloc[52217: 52217+44354, :].sort_values(by = 'completeTime')
b3 = tab.iloc[52217+44354:52217+44354+59681, :].sort_values(by = 'completeTime')
b4 = tab.iloc[52217+44354+59681: 52217+44354+59681+47293, :].sort_values(by = 'completeTime')
b5 = tab.iloc[52217+44354+59681+47293: , :].sort_values(by = 'completeTime')

,completeTime,role,event,lifecycle:transition,time:timestamp,action_code,question,activityNameNL,concept:name,dueDate,...,case,case:last_phase,case:SUMleges,case:case_type,case:IDofConceptCase,case:landRegisterID,case:caseProcedure,case:Includes_subCases,dateStop,prevdateFinished
0,2010-10-07 14:57:22,560872,register submission date request,complete,2009-11-18 00:00:00+01:00,01_HOOFD_010,5-10-2010 0:00:00,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-10 14:43:08+02:00,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-10-07 14:57:22
1,2010-10-07 14:57:22,560872,phase application received,complete,2009-11-20 14:57:14+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-11-30 16:22:53
2,2010-10-12 10:05:12,560925,phase application received,complete,2009-11-25 09:54:56+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
3,2010-10-12 10:05:12,560925,register submission date request,complete,2009-11-19 00:00:00+01:00,01_HOOFD_010,EMPTY,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-14 10:51:19+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
4,2010-10-12 10:05:12,560925,forward to the competent authority,complete,2009-11-25 09:56:15+01:00,01_HOOFD_040,False,doorsturen aan bevoegd gezag,01_HOOFD_040,2010-10-17 09:56:10+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96566,2019-07-24 00:00:00,560519,procedure change,complete,2019-05-22 15:00:04.931000+02:00,01_HOOFD_180,False,procedure verandering,01_HOOFD_180,NaN,...,case_id_1661,Beschikking gereed,70.81200,557669,NaN,NaN,NaN,NaN,NaN,2015-03-04 00:00:00
96567,2019-07-24 00:00:00,560519,ask stakeholders views,complete,2019-05-22 15:00:04.931000+02:00,01_HOOFD_430,False,belanghebbenden zienswijzen vragen,01_HOOFD_430,NaN,...,case_id_1661,Beschikking gereed,70.81200,557669,NaN,NaN,NaN,NaN,NaN,2015-03-04 00:00:00
96568,2019-07-24 00:00:00,560519,article 34 WABO applies,complete,2019-05-22 15:00:04.931000+02:00,09_AH_I_010,False,artikel 34 WABO van toepassing,09_AH_I_010,NaN,...,case_id_1661,Beschikking gereed,70.81200,557669,NaN,NaN,NaN,NaN,NaN,2015-03-04 00:00:00
96569,2019-07-24 00:00:00,560519,set decision status,complete,2019-05-22 15:00:04.931000+02:00,01_HOOFD_490_1a,EMPTY,instellen besluitstatus,01_HOOFD_490_1a,NaN,...,case_id_1661,Beschikking gereed,70.81200,557669,NaN,NaN,NaN,NaN,NaN,2015-03-04 00:00:00
96570,2019-07-24 00:00:00,560519,procedure change,complete,2019-05-22 15:00:04.931000+02:00,01_HOOFD_330,False,procedure verandering,01_HOOFD_330,NaN,...,case_id_1661,Beschikking gereed,70.81200,557669,NaN,NaN,NaN,NaN,NaN,2015-03-04 00:00:00

In [174]:
b1 = b1.append(b2, ignore_index = True)
b1 = b1.append(b3, ignore_index = True)
b1 = b1.append(b4, ignore_index = True)
b1 = b1.append(b5, ignore_index = True)

In [177]:
b1

,completeTime,role,event,lifecycle:transition,time:timestamp,action_code,question,activityNameNL,concept:name,dueDate,...,case,case:last_phase,case:SUMleges,case:case_type,case:IDofConceptCase,case:landRegisterID,case:caseProcedure,case:Includes_subCases,dateStop,prevdateFinished
0,2010-10-07 14:57:22,560872,register submission date request,complete,2009-11-18 00:00:00+01:00,01_HOOFD_010,5-10-2010 0:00:00,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-10 14:43:08+02:00,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-10-07 14:57:22
1,2010-10-07 14:57:22,560872,phase application received,complete,2009-11-20 14:57:14+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_196,Buiten behandeling gelaten,NaN,557669,2760933.0,NaN,NaN,N,NaN,2010-11-30 16:22:53
2,2010-10-12 10:05:12,560925,phase application received,complete,2009-11-25 09:54:56+01:00,01_HOOFD_015,EMPTY,fase aanvraag ontvangen,01_HOOFD_015,NaN,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
3,2010-10-12 10:05:12,560925,register submission date request,complete,2009-11-19 00:00:00+01:00,01_HOOFD_010,EMPTY,registratie datum binnenkomst aanvraag,01_HOOFD_010,2010-10-14 10:51:19+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
4,2010-10-12 10:05:12,560925,forward to the competent authority,complete,2009-11-25 09:56:15+01:00,01_HOOFD_040,False,doorsturen aan bevoegd gezag,01_HOOFD_040,2010-10-17 09:56:10+02:00,...,case_id_198,Vergunning verleend,116.79765,557669,NaN,NaN,NaN,J,NaN,2010-10-12 10:05:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262623,2032-10-01 00:00:00,560602,start decision phase decision permitting sent,complete,2035-02-26 12:50:11.539000+01:00,01_HOOFD_510_2a,EMPTY,instellen besluitfase:besluit vergunnen verzonden,01_HOOFD_510_2a,NaN,...,case_id_4600,Beschikking verzonden,14047.33000,557669,11550167.0,9202127.0,Uitgebreid,NaN,NaN,2015-03-03 00:00:00
262624,2032-10-01 00:00:00,560602,enter date advice on treatment of environmenta...,complete,2035-02-26 22:18:24.539000+01:00,01_HOOFD_450,3-3-2015 9:28:13,registreren datum advies omgevingsvergunning b...,01_HOOFD_450,NaN,...,case_id_4600,Beschikking verzonden,14047.33000,557669,11550167.0,9202127.0,Uitgebreid,NaN,NaN,2015-03-03 00:00:00
262625,2032-10-01 00:00:00,560602,enter date draft decisionenvironmental permit,complete,2035-02-26 22:18:34.539000+01:00,01_HOOFD_460,EMPTY,registreren datum ontwerpbesluit omgevingsverg...,01_HOOFD_460,NaN,...,case_id_4600,Beschikking verzonden,14047.33000,557669,11550167.0,9202127.0,Uitgebreid,NaN,NaN,2015-03-03 00:00:00
262626,2032-10-01 00:00:00,560602,date decision for inspection,complete,2035-02-26 22:19:27.539000+01:00,01_HOOFD_516,EMPTY,datum beschikking ter inzage,01_HOOFD_516,NaN,...,case_id_4600,Beschikking verzonden,14047.33000,557669,11550167.0,9202127.0,Uitgebreid,NaN,NaN,2015-03-03 00:00:00
262627,2032-10-01 00:00:00,560602,enrich draft decision,complete,2035-02-26 12:50:11.539000+01:00,01_HOOFD_455,False,ontwerpbeschikking verrijken,01_HOOFD_455,NaN,...,case_id_4600,Beschikking verzonden,14047.33000,557669,11550167.0,9202127.0,Uitgebreid,NaN,NaN,2015-03-03 00:00:00

In [169]:
#b1.head(-5) #2015-03-03
#b2.head(5) #2010-10-12: 2015-03-04, 2019-07-24, 1603
#b3 #2010-10-11: 2015-03-04, 2023-12-15, 3208
#b4#2010-10-07: 2015-03-04, 2028-05-11, 4817
#b5   2010-10-11: 2015-03-03, 2032-10-01, 6422
from datetime import datetime
b1diff = datetime.strptime( '2023-12-15', "%Y-%m-%d") - datetime.strptime( '2010-10-07', "%Y-%m-%d")
b1diff

datetime.timedelta(days=4817)

In [168]:
import datetime
b5['completeTime'] = [datetime.datetime.strptime(b5['completeTime'][i], "%Y-%m-%d %H:%M:%S") + datetime.timedelta(days=6422) for i in b5['completeTime'].index]
b5

TypeError: strptime() argument 1 must be str, not Timestamp

In [90]:
max(tab['completeTime'])

'2017-02-01 14:11:03.499000+00:00'

In [91]:
tab.sort_values(by = 'completeTime', inplace = True)

In [93]:
tab['completeTime']

0          2016-01-01 09:51:15.304000+00:00
1          2016-01-01 09:51:15.352000+00:00
2          2016-01-01 09:51:15.774000+00:00
3          2016-01-01 09:52:36.392000+00:00
4          2016-01-01 09:52:36.403000+00:00
                         ...
1071364    2017-02-01 14:00:30.347000+00:00
1071365    2017-02-01 14:01:24.191000+00:00
1169224    2017-02-01 14:09:03.331000+00:00
1191694    2017-02-01 14:10:52.793000+00:00
1191695    2017-02-01 14:11:03.499000+00:00
Name: completeTime, Length: 1202267, dtype: object

In [94]:
tab.head()

,Action,role,concept:name,EventOrigin,eventID,lifecycle:transition,completeTime,case:LoanGoal,case:ApplicationType,case,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,event
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15.304000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_Create Applicationcomplete
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15.352000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A_Submittedcomplete
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15.774000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W_Handle leadsschedule
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36.392000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W_Handle leadswithdraw
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36.403000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W_Complete applicationschedule

In [178]:
b1.to_csv(path_or_buf = '/Users/teddy/Documents/TU_e/ThirdYear/Quartile_4/BEP/edbn_BEP/Data/BPIC11.csv', index = False)

In [2]:
import pandas as pd
df = pd.read_csv('/Users/teddy/Documents/TU_e/ThirdYear/Quartile_4/BEP/edbn_BEP/Data/BPIC11.csv')

/Users/teddy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (10,11,12,13,14,15,16,17,18,19,22,23,26,46,47,49,50,51,52,65,66,67,79,80,81,88,90,97) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [183]:
datetime.strptime(df['completeTime'][df.shape[0]-1], "%Y-%m-%d %H:%M:%S")-datetime.strptime(df['completeTime'][0], "%Y-%m-%d %H:%M:%S")

datetime.timedelta(days=8029, seconds=32558)

In [3]:
df['completeTime'][0]

'2005/01/03 00:00:00.000'

In [4]:
df['completeTime'][df.shape[0]-1]

'2008/03/20 00:00:00.000'

In [5]:
df.sort_values(by = 'completeTime', inplace = True)

In [6]:
df

,case,event,startTime,completeTime,Specialism code:9,Specialism code:7,Specialism code:8,Diagnosis code:15,Diagnosis code:14,Diagnosis code:13,...,Specialism code:5,Specialism code:6,Specialism code:3,Specialism code:4,Activity code,role,event_Specialism code,Producer code,Section,Number of executions
0,0,1e consult poliklinisch,2005/01/03 00:00:00.000,2005/01/03 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,410100,Radiotherapy,61,SRTH,Section 5,1
24,4,sgpt - alat kinetisch,2005/01/03 00:00:00.000,2005/01/03 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7.0,7.0,370488G,General Lab Clinical Chemistry,86,CHE2,Section 4,1
25,4,hemoglobine foto-elektrisch,2005/01/03 00:00:00.000,2005/01/03 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7.0,7.0,370407.0,General Lab Clinical Chemistry,86,HAEM,Section 4,1
26,0,administratief tarief - eerste pol,2005/01/03 00:00:00.000,2005/01/03 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,419100,Radiotherapy,61,SRTH,Section 5,1
27,2,vervolgconsult poliklinisch,2005/01/03 00:00:00.000,2005/01/03 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7.0,NaN,411100,Internal Specialisms clinic,13,SIOG,Section 1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150256,518,aanname laboratoriumonderzoek,2008/03/20 00:00:00.000,2008/03/20 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,61.0,61.0,370000,General Lab Clinical Chemistry,86,CRLA,Section 4,1
150257,591,aanname laboratoriumonderzoek,2008/03/20 00:00:00.000,2008/03/20 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,370000,General Lab Clinical Chemistry,86,CRLA,Section 4,1
150258,591,sediment,2008/03/20 00:00:00.000,2008/03/20 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,370111,General Lab Clinical Chemistry,86,CRPO,Section 4,1
150260,518,bilirubine - totaal,2008/03/20 00:00:00.000,2008/03/20 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,61.0,61.0,370401C,General Lab Clinical Chemistry,86,CHE2,Section 4,1
150290,1142,ordertarief,2008/03/20 00:00:00.000,2008/03/20 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,379999,General Lab Clinical Chemistry,86,CRLA,Section 4,1